---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, junk]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Black in AI"
keywords:    "artificial intelligence, machine learning, computer visionn"
description: "Black in AI workshop home"
source_link: "https://github.com/blackinai/blackinai.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/favicon.ico"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)



### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#007299'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false


# for speaker individual pages: 
collections:
  speakers:
    output: true
    permalink: /:collection/:name
  segments:
    



